# Generated by Django 4.2.4 on 2023-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
